In [7]:
import mne, os
import numpy as np
from scipy.stats import pearsonr, ttest_ind

data_path = os.path.join(os.path.expanduser('~/'),'Desktop', 'FYP', 'code_env', 'eeg-notebooks','FYP', 'data_ordered', 'mne_raw')
file_audio1 = os.path.join(data_path, 'AudioVisual_04_1.fif')
file_shape1 = os.path.join(data_path, 'ShapeVisual_04_1.fif')
file_vibro1 = os.path.join(data_path, 'VibroVisual_04_1.fif')
file_audio2 = os.path.join(data_path, 'AudioVisual_04_2.fif')
file_shape2 = os.path.join(data_path, 'ShapeVisual_04_2.fif')
file_vibro2 = os.path.join(data_path, 'VibroVisual_04_2.fif')

# Load raw data for audio, vibro, and shape conditions
raw_audio1 = mne.io.read_raw(file_audio1, preload=True)
raw_vibro1 = mne.io.read_raw(file_vibro1, preload=True)
raw_shape1 = mne.io.read_raw(file_shape1, preload=True)
raw_audio2 = mne.io.read_raw(file_audio2, preload=True)
raw_vibro2 = mne.io.read_raw(file_vibro2, preload=True)
raw_shape2 = mne.io.read_raw(file_shape2, preload=True)

channels_of_interest = ["TP9", "AF7", "AF8", "TP10"]
max_length = 99328
duration = int(max_length / 256)

data_audio1 = raw_audio1.get_data(start=0, stop=duration, picks=channels_of_interest)
data_vibro1 = raw_vibro1.get_data(start=0, stop=duration, picks=channels_of_interest)
data_shape1 = raw_shape1.get_data(start=0, stop=duration, picks=channels_of_interest)
data_audio2 = raw_audio2.get_data(start=0, stop=duration, picks=channels_of_interest)
data_vibro2 = raw_vibro2.get_data(start=0, stop=duration, picks=channels_of_interest)
data_shape2 = raw_shape2.get_data(start=0, stop=duration, picks=channels_of_interest)


Opening raw data file C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\AudioVisual_04_1.fif...
    Range : 30 ... 99750 =      0.117 ...   389.648 secs
Ready.
Reading 0 ... 99720  =      0.000 ...   389.531 secs...
Opening raw data file C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\VibroVisual_04_1.fif...
    Range : 30 ... 100189 =      0.117 ...   391.363 secs
Ready.
Reading 0 ... 100159  =      0.000 ...   391.246 secs...
Opening raw data file C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\ShapeVisual_04_1.fif...
    Range : 30 ... 99577 =      0.117 ...   388.973 secs


C:\Users\matil\AppData\Local\Temp\ipykernel_17420\3253198677.py:14: RuntimeWarning: This filename (C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\AudioVisual_04_1.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw_audio1 = mne.io.read_raw(file_audio1, preload=True)
C:\Users\matil\AppData\Local\Temp\ipykernel_17420\3253198677.py:15: RuntimeWarning: This filename (C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\VibroVisual_04_1.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw_vibro1 = mne.io.read_raw(file_vibro1, preload=True)
C:\Users\matil\AppData\Local\Temp\ipyk

Ready.
Reading 0 ... 99547  =      0.000 ...   388.855 secs...
Opening raw data file C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\AudioVisual_04_2.fif...
    Range : 30 ... 99403 =      0.117 ...   388.293 secs
Ready.
Reading 0 ... 99373  =      0.000 ...   388.176 secs...
Opening raw data file C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\VibroVisual_04_2.fif...
    Range : 30 ... 99488 =      0.117 ...   388.625 secs
Ready.
Reading 0 ... 99458  =      0.000 ...   388.508 secs...
Opening raw data file C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\ShapeVisual_04_2.fif...
    Range : 30 ... 99509 =      0.117 ...   388.707 secs


C:\Users\matil\AppData\Local\Temp\ipykernel_17420\3253198677.py:17: RuntimeWarning: This filename (C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\AudioVisual_04_2.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw_audio2 = mne.io.read_raw(file_audio2, preload=True)
C:\Users\matil\AppData\Local\Temp\ipykernel_17420\3253198677.py:18: RuntimeWarning: This filename (C:\Users\matil/Desktop\FYP\code_env\eeg-notebooks\FYP\data_ordered\mne_raw\VibroVisual_04_2.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw_vibro2 = mne.io.read_raw(file_vibro2, preload=True)
C:\Users\matil\AppData\Local\Temp\ipyk

Ready.
Reading 0 ... 99479  =      0.000 ...   388.590 secs...


In [9]:
conditions = ["Audio", "Vibro", "Shape"]
# Compute correlation between conditions
correlation_matrix = np.zeros((len(channels_of_interest), len(channels_of_interest)))
correlation_p_values = np.zeros((len(channels_of_interest), len(channels_of_interest)))
for i, channel1 in enumerate(data_audio1):
    for j, channel2 in enumerate(data_vibro1):
        corr, p_value = pearsonr(channel1, channel2)
        correlation_matrix[i, j] = corr
        correlation_p_values[i, j] = p_value

# Perform autocorrelation analysis
autocorrelation_results = []
autocorrelation_p_values = []
for condition_data in [data_audio1, data_vibro1, data_shape1]:
    autocorrelation = np.zeros(len(channels_of_interest))
    autocorrelation_p = np.zeros(len(channels_of_interest))
    for i, channel_data in enumerate(condition_data):
        autocorr = np.correlate(channel_data, channel_data, mode='full')
        autocorrelation[i] = autocorr[len(channel_data)]
        _, autocorrelation_p[i] = pearsonr(channel_data[:-1], channel_data[1:])
    autocorrelation_results.append(autocorrelation)
    autocorrelation_p_values.append(autocorrelation_p)

# Perform t-tests between conditions
t_test_results = np.zeros((len(channels_of_interest), len(channels_of_interest), 3))
for i, channel1 in enumerate(data_audio1):
    for j, channel2 in enumerate(data_vibro1):
        _, p_value_1_2 = ttest_ind(channel1, channel2)
        _, p_value_1_3 = ttest_ind(channel1, data_shape1[i])
        _, p_value_2_3 = ttest_ind(channel2, data_shape1[j])
        t_test_results[i, j, 0] = p_value_1_2
        t_test_results[i, j, 1] = p_value_1_3
        t_test_results[i, j, 2] = p_value_2_3

# Print correlation matrix, autocorrelation results, and t-test results
print('Correlation Matrix:')
print(correlation_matrix)
print('Correlation p-values:')
print(correlation_p_values)
print('Autocorrelation Results:')
for i, result in enumerate(autocorrelation_results):
    print(f'Condition {conditions[i]}:')
    print(result)
    print(f'Autocorrelation p-values for Condition {conditions[i]}:')
    print(autocorrelation_p_values[i])
print('T-Test Results:')
print('p-values for Condition AUDIO vs. Condition VIBRO:')
print(t_test_results[:,:,0])
print('p-values for Condition AUDIO vs. Condition SHAPE:')
print(t_test_results[:,:,1])
print('p-values for Condition VIBRO vs. Condition SHAPE:')
print(t_test_results[:,:,2])


Correlation Matrix:
[[-0.10008748  0.01767705  0.13751891 -0.12672868]
 [ 0.07312679 -0.05452048 -0.13907994  0.01318137]
 [-0.1039243  -0.15851642 -0.24427145 -0.11463097]
 [ 0.01776392  0.05182681  0.14969814  0.00801309]]
Correlation p-values:
[[4.88288251e-02 7.28515332e-01 6.66832799e-03 1.24793450e-02]
 [1.50516733e-01 2.84052173e-01 6.06832771e-03 7.95776878e-01]
 [4.07554157e-02 1.73523243e-03 1.11578712e-06 2.39374646e-02]
 [7.27234089e-01 3.08554163e-01 3.11787779e-03 8.74982555e-01]]
Autocorrelation Results:
Condition Audio:
[37239.88490697  9342.0414792   5555.86082232 18134.00544224]
Autocorrelation p-values for Condition Audio:
[6.23676106e-156 7.33286356e-144 3.79727911e-163 9.56795586e-143]
Condition Vibro:
[2431263.72459108    5639.60643785    4900.04240382 1863122.32702615]
Autocorrelation p-values for Condition Vibro:
[1.61204609e-109 8.53508869e-137 9.21578723e-140 1.85487722e-120]
Condition Shape:
[306839.92283938  23897.18635559  39834.34439205 439214.58266793]
Au

In [10]:
conditions = ["Audio", "Vibro", "Shape"]

# Compute correlation between trials
correlation_matrix = np.zeros((len(channels_of_interest), len(channels_of_interest)))
correlation_p_values = np.zeros((len(channels_of_interest), len(channels_of_interest)))
for i, channel1 in enumerate(data_audio1):
    for j, channel2 in enumerate(data_audio2):
        corr, p_value = pearsonr(channel1, channel2)
        correlation_matrix[i, j] = corr
        correlation_p_values[i, j] = p_value

# Print correlation matrix, autocorrelation results, and t-test results
print("AUDIO, correlation between trials")
print('Correlation Matrix:')
print(correlation_matrix)
print('Correlation p-values:')
print(correlation_p_values)

#------------------
# Compute correlation between trials
correlation_matrix = np.zeros((len(channels_of_interest), len(channels_of_interest)))
correlation_p_values = np.zeros((len(channels_of_interest), len(channels_of_interest)))
for i, channel1 in enumerate(data_vibro1):
    for j, channel2 in enumerate(data_vibro2):
        corr, p_value = pearsonr(channel1, channel2)
        correlation_matrix[i, j] = corr
        correlation_p_values[i, j] = p_value

# Print correlation matrix, autocorrelation results, and t-test results
print("VIBRO, correlation between trials")
print('Correlation Matrix:')
print(correlation_matrix)
print('Correlation p-values:')
print(correlation_p_values)

#-------------------
# Compute correlation between trials
correlation_matrix = np.zeros((len(channels_of_interest), len(channels_of_interest)))
correlation_p_values = np.zeros((len(channels_of_interest), len(channels_of_interest)))
for i, channel1 in enumerate(data_shape1):
    for j, channel2 in enumerate(data_shape2):
        corr, p_value = pearsonr(channel1, channel2)
        correlation_matrix[i, j] = corr
        correlation_p_values[i, j] = p_value

# Print correlation matrix, autocorrelation results, and t-test results
print("SHAPE, correlation between trials")
print('Correlation Matrix:')
print(correlation_matrix)
print('Correlation p-values:')
print(correlation_p_values)


AUDIO, correlation between trials
Correlation Matrix:
[[-0.14536775  0.11779482  0.11011659 -0.14279515]
 [ 0.23779336 -0.03691876 -0.0668099   0.2368899 ]
 [ 0.04086453  0.09446109  0.0685466   0.02499362]
 [-0.0443669   0.19479777  0.12089253 -0.01738466]]
Correlation p-values:
[[4.11211334e-03 2.02928812e-02 3.01095865e-02 4.83060156e-03]
 [2.16914363e-06 4.68380812e-01 1.89107434e-01 2.37633326e-06]
 [4.22161918e-01 6.30522750e-02 1.77838455e-01 6.23564036e-01]
 [3.83461456e-01 1.12578838e-04 1.72017220e-02 7.32833267e-01]]
VIBRO, correlation between trials
Correlation Matrix:
[[ 0.10699042  0.04998575  0.18965551  0.13659027]
 [ 0.12002131 -0.05119364 -0.08349459  0.09529049]
 [ 0.02964122 -0.09484944 -0.06702521  0.01873224]
 [ 0.0913935   0.05500842  0.15767094  0.09293032]]
Correlation p-values:
[[3.51420519e-02 3.26078958e-01 1.71353507e-04 7.04996063e-03]
 [1.80265140e-02 3.14509918e-01 1.00545482e-01 6.07627234e-02]
 [5.60493602e-01 6.19715521e-02 1.87682555e-01 7.13004355e-